language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'
    - DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test'
    - DB=sqlite db_dsn='sqlite:///:memory:'

  global:
    - DEFAULT=1
    - CODECOVERAGE=0

matrix:
  fast_finish: true

  include:
    - php: 7.3
      env: CODECOVERAGE=1 DEFAULT=0

    - php: 7.1
      env: PHPCS=1 DEFAULT=0

    - php: 7.1
      env: PHPSTAN=1 DEFAULT=0

    - php: 5.6
      env: PREFER_LOWEST=1

before_script:
  - if [[ $CODECOVERAGE = 0 ]]; then phpenv config-rm xdebug.ini; fi

  - if [[ $PREFER_LOWEST != 1 ]]; then composer update --no-interaction ; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --no-interaction --prefer-lowest --prefer-stable; fi

  - if [[ $PHPSTAN = 1 ]]; then composer require phpstan/phpstan; fi

  - if [[ $DB = 'mysql' ]]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi
  - if [[ $DB = 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi

  - if [[ $PHPCS = 1 ]]; then composer require cakephp/cakephp-codesniffer:"^3.0"; fi
  - if [[ $PHPSTAN = 1 ]]; then composer require phpstan/phpstan; fi

script:
  - if [[ $DEFAULT = 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $CODECOVERAGE = 1 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi

  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi
  - if [[ $PHPSTAN = 1 ]]; then vendor/bin/phpstan analyse src; fi

after_success:
  - if [[ $CODECOVERAGE ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
